### ISSUE TITLE
manifest

### ISSUE THREAD

**Issue by jeanfrancis** [toocool/tripexpress#14]
Add the option to print the list of passenger for a given bus

**Comment by toocool** [comment]
This option is going to be implemented this week.

**Comment by toocool** [comment]
2a1c94311647a16fe9cd15ad711de82f2e587818 feature updated now there is a new button where a list of passengers can be seen

**Comment by jeanfrancis** [comment]
Would be good to have an option to print it as PDF and have included seat number
