### ISSUE TITLE
Improve Statistics page with more details

### ISSUE THREAD

**Issue by jeanfrancis** [toocool/tripexpress#23]
Improve the Statistics page with more details

**Comment by jeanfrancis** [comment]
Agent Booking Detail: The Report will Display Booking Information of the Booking Done by Postpaid, Prepaid Or Global Agent.
Agent Outstanding: The Report will display Cash Tally for the Bookings and cancellation done by any Local Postpaid Agent.
Attendant Memo: The Report will display Pick Up and Drop Point information for all the Bookings done by any Employee, Local Agent and Global Agent.
Bus Departure: The Report will display information about Total Tickets Booked in selected Schedule and Total Amount of which Tickets are Booked.
Cash Tally Report: The Report will display Cash Tally of the Booking and Cancellation done by Employee.
Collection from Agent: The Report will display information about Total Amount collected by Employee from Agent.
Daily Departure Register Report: The Report will display information about the Main Route Schedule for which Vehicle Scheduling is done between selected Date Range.
Non-Reporting Passenger Report: The Report will display information about the Tickets, which are marked as Non Reporting while doing Ticket Counter Audit.
Office Wise Sales: The Report will display information about the Booking done by each Employees of specific Branch.
Passenger List: The Report will display information about the Passengers for whom Tickets are booked under selected Schedule.
Passenger Scheme Report: The Report will display information about Passenger Scheme applied and Discount Amount obtained during Booking.
Quota Seats Converted as Booking: The Report will display information about the Quota Seats assigned to user and Booking done by user under that Quota Seats.
Rate Change: The Report will display information about the rate change done by user while booking the Tickets.
Schedule Cancellation: The Report will display information about the Tickets cancelled in selected Schedule.
Schedule Chart Status: The Report will display Booking Chart status for selected Schedule.
Ticket Counter Hand Over Register: The Report will display details of Counter sent by Operator to Employee.
Vehicle Usability: The Report will display information about Vehicle Registration No, No of Days it was used, Not Used, No of Trips it did, No of KM it covered.

**Comment by toocool** [comment]
Some of the above are done
