### ISSUE TITLE
Agent Management feature

### ISSUE THREAD

**Issue by jeanfrancis** [toocool/tripexpress#27]
Agent Management should provides facility to Add, Edit and View Agent Details.

Operator can create Prepaid Agent OR Postpaid Agent.
Agent can also create Sub Agent under him/her.
User can also Block the Agent due to some specific Reason by clicking on Block icon under Block column.
Agent created by Operator OR Sub Agent created under any specific Agent can do Booking by Login.
Booking can only be done by Agents, which are Active and Not Blocked.

**Comment by toocool** [comment]
added the function to block/unblock agents (members)
