### ISSUE TITLE
Payment gateway

### ISSUE THREAD

**Issue by jeanfrancis** [toocool/tripexpress#3]
Any planned integration with a payment gateway ?

**Comment by jeanfrancis** [comment]
suggestions of Paypal , https://bitpay.com and https://stripe.com

**Comment by toocool** [comment]
paypal and skrill are going be implemented after the front end side is going to be implemented

**Comment by jeanfrancis** [comment]
PayPal, Authorize.NET integration
Cash payments
Credit card processing
Bank account
Deposit payments
Tax payments

should be also the features
